# Generated by scripts/install.sh. Customize these values after installation.
{
  user = "cbrst";
  hostName = "Asgard";
  timeZone = "Europe/Berlin";
  keyMap = "us";
  # Opt into the Noctalia shell (home/cbrst.nix only defines the option when
  # this is true). Disable to use plain Hyprland + hyprpaper instead.
  noctalia = true;
}
