#!/usr/bin/env bash

# Install this configuration on a selected blank disk. It never touches disks
# other than the one explicitly selected and confirmed below.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target_root="/mnt"

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

require_root() {
  [[ ${EUID} -eq 0 ]] || die "run this script as root from the NixOS installer"
}

require_uefi() {
  [[ -d /sys/firmware/efi/efivars ]] || die "boot the NixOS installer in UEFI mode"
}

prompt_value() {
  local prompt=$1
  local default=$2
  local value

  read -r -p "${prompt} [${default}]: " value
  printf '%s' "${value:-${default}}"
}

validate_identifier() {
  [[ $1 =~ ^[a-z][a-z0-9-]*$ ]] || die "hostname must contain lowercase letters, digits, and hyphens"
}

validate_username() {
  [[ $1 =~ ^[a-z_][a-z0-9_-]*$ ]] || die "username must contain lowercase letters, digits, underscores, or hyphens"
}

validate_timezone() {
  [[ $1 =~ ^[A-Za-z0-9_+./-]+$ && ${1} != *".."* ]] || die "timezone contains unsupported characters"
}

timezone_exists() {
  timedatectl list-timezones | grep -Fxq "$1" || [[ -e "/usr/share/zoneinfo/$1" ]]
}

validate_keymap() {
  [[ $1 =~ ^[A-Za-z0-9,_+-]+$ ]] || die "keyboard layout contains unsupported characters"
}

partition_path() {
  local disk=$1
  local number=$2

  if [[ ${disk} =~ (nvme|mmcblk|loop) ]]; then
    printf '%sp%s' "${disk}" "${number}"
  else
    printf '%s%s' "${disk}" "${number}"
  fi
}

list_disks() {
  lsblk --nodeps --paths --noheadings --raw --output PATH,SIZE,MODEL,SERIAL,TYPE | \
    while read -r path size model serial type; do
      [[ ${type} == "disk" ]] || continue
      printf '%s|%s|%s|%s\n' "${path}" "${size}" "${model:-unknown}" "${serial:-unknown}"
    done
}

select_disk() {
  local -a disks=()
  local entry selected confirmation mountpoints
  local index=1

  while IFS= read -r entry; do
    disks+=("${entry}")
    IFS='|' read -r path size model serial <<<"${entry}"
    printf '  %d) %s  %s  model=%s  serial=%s\n' "${index}" "${path}" "${size}" "${model}" "${serial}"
    ((index += 1))
  done < <(list_disks)

  [[ ${#disks[@]} -gt 0 ]] || die "no writable disks were found"
  read -r -p "Select the disk to erase [1-${#disks[@]}]: " selected
  if ! [[ ${selected} =~ ^[0-9]+$ ]] || (( selected < 1 || selected > ${#disks[@]} )); then
    die "invalid disk selection"
  fi

  IFS='|' read -r target_disk _ <<<"${disks[$((selected - 1))]}"
  [[ $(lsblk --nodeps --noheadings --output TYPE "${target_disk}") =~ disk ]] || die "selected path is not a disk"

  mountpoints="$(lsblk --noheadings --raw --output MOUNTPOINTS "${target_disk}")"

  if target_is_prepared; then
    printf '\n%s already has the NixOS installer layout. It can be resumed without erasing it.\n' "${target_disk}"
    read -r -p "Resume the previous installation on ${target_disk}? [Y/n]: " confirmation
    [[ ${confirmation,,} != "n" && ${confirmation,,} != "no" ]] || die "resume was declined"
    resume_installation=true
    return
  fi

  if [[ ${mountpoints} =~ [^[:space:]] ]]; then
    die "${target_disk} or one of its partitions is mounted; refuse to erase it"
  fi

  printf '\nOnly %s will be erased. Every other disk, including the shared data disk, is ignored.\n' "${target_disk}"
  read -r -p "Type ERASE ${target_disk} to continue: " confirmation
  [[ ${confirmation} == "ERASE ${target_disk}" ]] || die "confirmation did not match"
}

target_is_prepared() {
  local boot_partition root_partition

  boot_partition="$(partition_path "${target_disk}" 1)"
  root_partition="$(partition_path "${target_disk}" 2)"
  [[ $(blkid --match-token LABEL=NIXOS_BOOT --output device 2>/dev/null) == "${boot_partition}" ]] || return 1
  [[ $(blkid --match-token LABEL=NIXOS_ROOT --output device 2>/dev/null) == "${root_partition}" ]] || return 1
  [[ $(blkid --match-token LABEL=NIXOS_ROOT --output value --match-tag TYPE "${root_partition}" 2>/dev/null) == "btrfs" ]] || return 1
}

write_local_config() {
  local user=$1
  local hostname=$2
  local timezone=$3
  local keymap=$4

  cat > "${target_root}/etc/nixos/hosts/local.nix" <<EOF
# Generated by scripts/install.sh. Customize these values after installation.
{
  user = "${user}";
  hostName = "${hostname}";
  timeZone = "${timezone}";
  keyMap = "${keymap}";
}
EOF
}

write_hardware_config() {
  local boot_partition=$1
  local root_partition=$2

  cat > "${target_root}/etc/nixos/hosts/hardware-configuration.nix" <<EOF
{ modulesPath, ... }:
{
  imports = [ "\${modulesPath}/installer/scan/not-detected.nix" ];

  boot.initrd.availableKernelModules = [ "ahci" "nvme" "sd_mod" "usb_storage" "usbhid" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];

  fileSystems."/" = {
    device = "${root_partition}";
    fsType = "btrfs";
    options = [ "subvol=@" "compress=zstd" ];
  };
  fileSystems."/home" = {
    device = "${root_partition}";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd" ];
  };
  fileSystems."/nix" = {
    device = "${root_partition}";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd" ];
  };
  fileSystems."/var/log" = {
    device = "${root_partition}";
    fsType = "btrfs";
    options = [ "subvol=@log" "compress=zstd" ];
  };
  fileSystems."/boot" = {
    device = "${boot_partition}";
    fsType = "vfat";
  };
}
EOF
}

enroll_secure_boot_keys() {
  if [[ ! -d /sys/firmware/efi/efivars ]]; then
    die "Secure Boot keys can only be enrolled when the installer is booted in UEFI mode"
  fi

  nixos-enter --root "${target_root}" -c 'sbctl create-keys'
  if ! nixos-enter --root "${target_root}" -c 'sbctl enroll-keys --microsoft'; then
    die "Secure Boot key enrollment failed. Reboot into firmware setup, enable Setup Mode or clear the platform Secure Boot keys, then run: nixos-enter --root /mnt -c '"'"'sbctl enroll-keys --microsoft'"'"'"
  fi
}

format_target() {
  local boot_partition root_partition

  boot_partition="$(partition_path "${target_disk}" 1)"
  root_partition="$(partition_path "${target_disk}" 2)"

  wipefs --all --force "${target_disk}"
  sgdisk --zap-all "${target_disk}"
  sgdisk --new=1:1MiB:+1GiB --typecode=1:ef00 --change-name=1:NIXOS_BOOT "${target_disk}"
  sgdisk --new=2:0:0 --typecode=2:8300 --change-name=2:NIXOS_ROOT "${target_disk}"
  partprobe "${target_disk}"
  udevadm settle

  mkfs.fat -F 32 -n NIXOS_BOOT "${boot_partition}"
  mkfs.btrfs -f -L NIXOS_ROOT "${root_partition}"

  mount "${root_partition}" "${target_root}"
  btrfs subvolume create "${target_root}/@"
  btrfs subvolume create "${target_root}/@home"
  btrfs subvolume create "${target_root}/@nix"
  btrfs subvolume create "${target_root}/@log"
  umount "${target_root}"

  mount -o compress=zstd,subvol=@ "${root_partition}" "${target_root}"
  mkdir -p "${target_root}/home" "${target_root}/nix" "${target_root}/var/log" "${target_root}/boot"
  mount -o compress=zstd,subvol=@home "${root_partition}" "${target_root}/home"
  mount -o compress=zstd,subvol=@nix "${root_partition}" "${target_root}/nix"
  mount -o compress=zstd,subvol=@log "${root_partition}" "${target_root}/var/log"
  mount "${boot_partition}" "${target_root}/boot"
}

mount_target() {
  local boot_partition root_partition

  boot_partition="$(partition_path "${target_disk}" 1)"
  root_partition="$(partition_path "${target_disk}" 2)"

  mkdir -p "${target_root}"
  mountpoint -q "${target_root}" || mount -o compress=zstd,subvol=@ "${root_partition}" "${target_root}"
  mkdir -p "${target_root}/home" "${target_root}/nix" "${target_root}/var/log" "${target_root}/boot"
  mountpoint -q "${target_root}/home" || mount -o compress=zstd,subvol=@home "${root_partition}" "${target_root}/home"
  mountpoint -q "${target_root}/nix" || mount -o compress=zstd,subvol=@nix "${root_partition}" "${target_root}/nix"
  mountpoint -q "${target_root}/var/log" || mount -o compress=zstd,subvol=@log "${root_partition}" "${target_root}/var/log"
  mountpoint -q "${target_root}/boot" || mount "${boot_partition}" "${target_root}/boot"
}

main() {
  local user hostname timezone keymap boot_partition root_partition
  resume_installation=false

  require_root
  require_uefi
  command -v nixos-generate-config >/dev/null || die "run from the NixOS installation ISO"
  [[ -f "${repo_root}/flake.nix" ]] || die "run from the root of this repository"

  printf '%s\n' "Available disks:"
  select_disk

  user="$(prompt_value "Username" "cbrst")"
  hostname="$(prompt_value "Hostname" "Asgard")"
  timezone="$(prompt_value "Timezone" "Europe/Berlin")"
  keymap="$(prompt_value "Keyboard layout" "us")"
  validate_username "${user}"
  validate_identifier "${hostname,,}"
  validate_timezone "${timezone}"
  validate_keymap "${keymap}"
  timezone_exists "${timezone}" || die "unknown timezone: ${timezone}"

  if [[ ${resume_installation} == true ]]; then
    mount_target
  else
    format_target
  fi
  boot_partition="$(partition_path "${target_disk}" 1)"
  root_partition="$(partition_path "${target_disk}" 2)"
  mkdir -p "${target_root}/etc/nixos"
  cp -a "${repo_root}/." "${target_root}/etc/nixos/"
  write_hardware_config "${boot_partition}" "${root_partition}"
  write_local_config "${user}" "${hostname}" "${timezone}" "${keymap}"

  nixos-install --flake "path:${target_root}/etc/nixos#default"
  enroll_secure_boot_keys
  printf '\nInstallation complete. Secure Boot keys are enrolled. Reboot, select NixOS from systemd-boot, then log in as %s.\n' "${user}"
}

main "$@"
